### ISSUE TITLE
Unable to add an EXDATE

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#58]
```
$foo = $calendar->getComponent('FA331FB9-19EC-408E-992D-3C3B67D90B4F');
$foo->setExdate([  
	    'year'  => 2017,
            'month' => 1,
            'day'   => 1,
            'hour'  => 1,
            'min'   => 1,
            'sec'   => 1,
            'tz'    => 'America/New_York'
]);
```

That results in this:

PHP Notice:  Uninitialized string offset: 8 in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/util.php on line 2084

Notice: Uninitialized string offset: 8 in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/util.php on line 2084
PHP Notice:  Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237

Notice: Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237
PHP Notice:  Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237

Notice: Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237
PHP Notice:  Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237

Notice: Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237
PHP Notice:  Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237

Notice: Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237
PHP Notice:  Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237

Notice: Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237
PHP Notice:  Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237

Notice: Undefined variable: exdatea in /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php on line 237
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to kigkonsult\iCalcreator\vcalendarSortHandler::sortExdate1() must be of the type array, null given in /private/tmp/f/vendor/kigkonsult/icalcreator/src/vcalendarSortHandler.php:173
Stack trace:
#0 [internal function]: kigkonsult\iCalcreator\vcalendarSortHandler::sortExdate1(NULL, NULL)
#1 /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php(129): usort(Array, Array)
#2 /private/tmp/f/vendor/kigkonsult/icalcreator/src/traits/EXDATEtrait.php(51): kigkonsult\iCalcreator\util\utilRexdate::formatExdate(Array, true)
#3 /private/tmp/f/vendor/kigkonsult/icalcreator/src/vevent.php(154): kigkonsult\iCalcreator\vevent->createExdate()
#4 /private/tmp/f/f(27): kigkonsult\iCalcreator\vevent->createComponent()
#5 {main}
  thrown in /private/tmp/f/vendor/kigkonsult/icalcreator/src/vcalendarSortHandler.php on line 173

Fatal error: Uncaught TypeError: Argument 1 passed to kigkonsult\iCalcreator\vcalendarSortHandler::sortExdate1() must be of the type array, null given in /private/tmp/f/vendor/kigkonsult/icalcreator/src/vcalendarSortHandler.php:173
Stack trace:
#0 [internal function]: kigkonsult\iCalcreator\vcalendarSortHandler::sortExdate1(NULL, NULL)
#1 /private/tmp/f/vendor/kigkonsult/icalcreator/src/util/utilRexdate.php(129): usort(Array, Array)
#2 /private/tmp/f/vendor/kigkonsult/icalcreator/src/traits/EXDATEtrait.php(51): kigkonsult\iCalcreator\util\utilRexdate::formatExdate(Array, true)
#3 /private/tmp/f/vendor/kigkonsult/icalcreator/src/vevent.php(154): kigkonsult\iCalcreator\vevent->createExdate()
#4 /private/tmp/f/f(27): kigkonsult\iCalcreator\vevent->createComponent()
#5 {main}
  thrown in /private/tmp/f/vendor/kigkonsult/icalcreator/src/vcalendarSortHandler.php on line 173

**Comment by grosch** [comment]
OK, figured out the syntax.  Strange choice you made there :)
